### PR TITLE
Decode urls safely to avoid crashes

### LINKED ISSUE #510: malformed URI crashes Sable and won't let you view the room again it was sent in
### Describe the bug

I tried sending a encoded link (was reporting an xss in his website) and now entering a DM crashes sable. https://REDACTED/display/?t=%3Csvg/onload=alert(%22message%C4%99%20glow%C4%99%20message%C5%82message.%22);%3E

### Reproduction

1. Send encoded link
2. Crash

### Expected behavior

_No response_

### Platform and versions

```shell
- OS: Linux armv81
- Browser: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Mobile Safari/537.36
- Sable: v1.12.2-dev (8f46cff)
```

### Additional context

# Automated Bug Report
Error occurred in the application.

## Error Message
```
URI malformed
```

## Stacktrace
```
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at https://sable.sugary.gay/assets/index-D7zWf1Iz.js:82314:32
    at mI.render (https://sable.sugary.gay/assets/index-D7zWf1Iz.js:62955:65)
    at nDe (https://sable.sugary.gay/assets/index-D7zWf1Iz.js:63238:19)
    at https://sable.sugary.gay/assets/index-D7zWf1Iz.js:63254:46
    at https://sable.sugary.gay/assets/index-D7zWf1Iz.js:250:14
    at https://sable.sugary.gay/assets/index-D7zWf1Iz.js:219:19
    at O (https://sable.sugary.gay/assets/index-D7zWf1Iz.js:203:35)
    at O (https://sable.sugary.gay/assets/index-D7zWf1Iz.js:209:15)
    at B (https://sable.sugary.gay/assets/index-D7zWf1Iz.js:218:14)
```

### PR DESCRIPTION
**Pull request by 7w1**
### Description

Fixes #510 

#### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### AI disclosure:

- [ ] Partially AI assisted (clarify which code was AI assisted and briefly explain what it does).
- [ ] Fully AI generated (explain what all the generated code does in moderate detail).

### CODE REVIEW

**Review by rmamet — APPROVED** [review]

File: src/app/plugins/react-custom-html-parser.tsx [hunk 1]
```diff
@@ -60,6 +60,14 @@ export const LINKIFY_OPTS: LinkifyOpts = {
   ignoreTags: ['span'],
 };
 
+const safeDecodeUrl = (url: string) => {
```
Comment (dozro) [inline src/app/plugins/react-custom-html-parser.tsx]: duplicated code to https://github.com/SableClient/Sable/pull/512/changes#diff-dcc98aa7f0f573ba78fe68798849d7f99ab4c9926bddc9973d1b24af8c68ca64R26

**Review by dozro — APPROVED** [review]

**Review by rmamet — APPROVED** [review]

**Comment by 7w1** [comment]
such an unnecessary title change smh

**Comment by dozro** [comment]
> such an unnecessary title change smh

hehe
